name = "search-shortcuts"
account_id = "5b7e0a3aca26fcb4f1b44582f1853360"
workers_dev = false
route = "search.fullylegit.dev/*"
compatibility_date = "2021-08-27" # required
compatibility_flags = [ "formdata_parser_supports_files" ] # required
main   = "build/worker/shim.mjs"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[[rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
