[package]
name = "search-shortcuts"
version = "0.1.0"
authors = ["user <40304161+fullylegit@users.noreply.github.com>"]
edition = "2021"

[dependencies]
psl = "2.1.2"
thiserror = "1.0.22"
url = "2.2.0"

[dev-dependencies]
test-case = "3.3.1"
